### ISSUE TITLE
Error in decompyleMePlease

### ISSUE THREAD

**Issue by solomonbstoner** [ntu-offsec/recruitment2018#1]
I believe there is a problem with the `decompyleMePlease` challenge. The flag shows `"SCSE-"` only. Plz fix. The file is [downloaded from here](https://ntu-offsec.github.io/recruitment2018/challenges/Reversing/decompyleMe/decompyleMe.zip).

**Comment by cExplr** [comment]
OK. Please ignore this. Now you can [download it here](https://ntu-offsec.github.io/recruitment2018/challenges/Reversing/decompyleMe/prob.pyc). Thanks for pointing this out!
